### ISSUE TITLE
Allow digit characters in 

### ISSUE THREAD

**Issue by t-prod** [AaronDDM/XMLBuilder#14]
Hi,

I would like to name an attribute with digits like this : `<AD1XCVD>`.
It does not work cause there is a preg_replace that prevents it , so I obtain this `<ADXCVD>`

vendor\aaronddm\xml-builder\lib\XMLElementData.php  we have this line

`$name = preg_replace('/([^a-zA-Z\-\_\:]+)/', '', $name);`

How can I do to allow it please ?

**Comment by t-prod** [comment]
I think it could be nice to allow digits here and to change the preg_replace.
Could you do it ?

Thanks again

**Comment by t-prod** [comment]
We could do this :

`$name = preg_replace('/([^a-zA-Z0-9\-\_\:]+)/', '', $name);`

**Comment by AaronDDM** [comment]
Yeah, this needs improvement - i'll have a look.

**Comment by t-prod** [comment]
Hi AaronDDM,

Do you think you can add this to allow the missing characters we can have ?
Thanks

**Comment by AaronDDM** [comment]
Yep, will have an update this weekend!

**Comment by AaronDDM** [comment]
Hey @t-prod check out v2.0.2 and let me know if that works!

Thanks
