### ISSUE TITLE
Adding a custom DOCTYPE tag

### ISSUE THREAD

**Issue by zietbukuel** [AaronDDM/XMLBuilder#7]
I need to create an XML file that has the following Doctype:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE VAR_COMP TXT "/path/to/file.dtd">
```

How can add this Doctype with this library?
Thanks.

**Comment by AaronDDM** [comment]
You cannot at the moment, but I'm going to look into adding support for this.

**Comment by AaronDDM** [comment]
Hey @zietbukuel ,

Check out https://github.com/AaronDDM/XMLBuilder#example-custom-xmlwriter-instance

Thanks!

**Comment by zietbukuel** [comment]
Thank you so much. Works like a charm.
